---
title: "HW3_part2"
output: html_document
---
###法國vs阿根廷PTT的TFIDF -> PCA -> K-means
```{r}
library(bitops)
library(httr)
library(XML)
library(RCurl)
library(tm)
library(NLP)
library(tmcn)
library(jiebaRD)
library(jiebaR)
library(dplyr)
library(tm)
library(knitr)
library(ggplot2)
library(factoextra)
library(Matrix)
library(tmcn)
```

1.叫出「法國對阿根廷賭盤開始」~「賽事結束」的的世足板爬蟲
```{r}
docs.corpus <- Corpus(DirSource("./DATA"))
docs.seg <- tm_map(docs.corpus, segmentCN)
docs.tdm <- TermDocumentMatrix(docs.seg)
```

2.進行TFIDF
```{r}
docs.tf <- apply(as.matrix(docs.tdm), 2, function(word) { word/sum(word) })
idf <- function(doc) {
  return ( log2( length(doc)+1 / nnzero(doc)) )
}
docs.idf <- apply(as.matrix(docs.tdm), 1, idf)
docs.tfidf <- docs.tf * docs.idf
```

###PCA
```{r}
docs.pca <- prcomp(docs.tfidf, scale = T)
```

繪圖  
1.將特徵值標示在對應的特徵向量
```{r}
fviz_eig(docs.pca)
```
2.用不同方式呈現在圖表上
```{r}
fviz_pca_ind(docs.pca, geom.ind = c("point"), col.ind = "cos2")
fviz_pca_var(docs.pca, col.var = "contrib")
fviz_pca_biplot(docs.pca, geom.ind = "point")
```
```{r}
docs.eig <- get_eig(docs.pca)
docs.var <- get_pca_var(docs.pca)
docs.ind <- get_pca_ind(docs.pca)
```

###Kmeans
1.選擇K值(K群)
```{r}
ind.coord2 <- docs.ind$coord[, 1:2]
wss <- c()
for (i in 1:10) { wss[i] <- kmeans(ind.coord2, i)$tot.withinss }
plot(wss, type = "b")
```

2.中心點重計算
```{r}
km <- kmeans(ind.coord2, 3)
plot(ind.coord2, col = km$cluster)
points(km$centers, col = 1:3, pch = 8, cex = 2)
```
